### ISSUE TITLE
1.18.2 Update

### ISSUE THREAD

**Issue by ZeTioZ** [DanielTheDev/NPC#3]
Hi,
I updated your code for the 1.18.2.

You just have to change the imports and to get the entity counter field, change the "b" to "c" when you initialize the atomic integer.

More info on the mapping here: https://minidigger.github.io/MiniMappingViewer/#/mojang

**Comment by DanielTheDev** [comment]
Thank you for advising me how to update the code. 
I will soon perform some unit tests to check whether there aren't any more changes made.
Until then, I will have to wait until the bukkit/spigot release of the Minecraft version 1.18.2.
