### ISSUE TITLE
1.19 Update

### ISSUE THREAD

**Issue by ZeTioZ** [DanielTheDev/NPC#5]
Hello,
Sorry to bother you. I was trying to update your lib on 1.19 but unfortunately I run into some issue with the pose. I don't really get how to make it work ^^' Looks like it needs an OptionalInt instead of the actual pose. I don't really understand what's the issue, and the little website for the remap is down so I can't really look into it ^^'. So,  I was wondering if you could update the lib to 1.19. Thanks

**Comment by DanielTheDev** [comment]
Yes, I have been working on the 1.19 NPC util with additional functions.
However, since 1.19 is a bit different, I have to test every functionality before publishing the newest version.
Therefore, it will take some time for me to finish it, but I am aiming for a release before Friday.

**Comment by ZeTioZ** [comment]
Thanks a lot for your hard work!

**Comment by DanielTheDev** [comment]
Hey [ZeTioZ](https://github.com/ZeTioZ)

Good news. I will release the NPC-1.19 utility tonight before 12 am CEST.
I will post the link of the spigot post in here around that time.

https://www.spigotmc.org/threads/advanced-npc-util-1-19-packets.563335/

Thank you for your patience.

Kind regards,
Daniël.

**Comment by ZeTioZ** [comment]
Thanks a lot !
