### ISSUE TITLE
Setting NPC skin doesn't work

### ISSUE THREAD

**Issue by ZeTioZ** [DanielTheDev/NPC#6]
Hi,
I've been testing the update of the lib and I found that the skins applied by either UUID or Name isn't working. It does work if I modify directly the GameProfile though and provide the texture and signature.

I'm using your gist of the 1.19 (updated for 1.19.1)

**Comment by DanielTheDev** [comment]
Can you send me the code you are using?

**Comment by ZeTioZ** [comment]
Sure, it's this one https://gist.github.com/DanielTheDev/96862d0f79d24d8df029648ddc45c2c0

I tried to debug it, and it seem that it doesn't call the runnable at all. That's quite strange.

**Comment by DanielTheDev** [comment]
My bad, I understand the confusion.
What I meant was if you can send me your code.
I just want to double check it is not related to a code mistake of yours. 

Have you tried adding .async() or .sync() at the end of the skin method. That is the final call to initiate the fetching procedure.

**Comment by ZeTioZ** [comment]
Here is how I call the setskin function : NPC#setSkinByUUID(instance, player.getUniqueId());

```java
menuNPC.setDisplayName(player.getName());
menuNPC.getProfile().getProperties().removeAll("textures");
menuNPC.setSkinByUUID(instance, player.getUniqueId());
menuNPC.reloadNPC(player);
```

Here is what I tried to debug your code:
```java
public BukkitCompletable<NPC> setSkinByUUID(Plugin plugin, UUID uuid) {
  return BukkitCompletable.supplyASync(plugin, ()->{
	  final SkinTextures skin = SkinTextures.getByUUID(plugin, uuid).getSync();
	  plugin.getLogger().info("Skin: " + skin);
	  plugin.getLogger().info("Signature: " + skin.signature);
	  plugin.getLogger().info("Texture: " + skin.texture);
	  this.setSkin(skin);
	  return NPC.this;
  });
}
```

EDIT: Ok, I'm an idiot... I read the code of the lib once again and yes. I forgot the ".getSync()" after  the methods call :). It works, thanks!

**Comment by DanielTheDev** [comment]
Okay, I understand the problem. The method setSkin returns the procedure object. Meaning that you can set your own callback to it and run it async or sync. The reason why it does nothing is because setting skin automatically is not possible since you cannot call it anytime you like. For instance, if you call it after you spawned the NPC, you have to destroy the NPC and it therefore loses at it properties that are stored client sided. 
Concluding, the util provides you the method for setting the skin and it is up to you what you do next, if you call it sync or async, etc.

If this still confuses you, we can look at your code together to accomplish your desired outcome.

Note: never call getSync when on the main bukkit thread.

Kind regards.

**Comment by ZeTioZ** [comment]
> Okay, I understand the problem. The method setSkin returns the procedure object. Meaning that you can set your own callback to it and run it async or sync. The reason why it does nothing is because setting skin automatically is not possible since you cannot call it anytime you like. For instance, if you call it after you spawned the NPC, you have to destroy the NPC and it therefore loses at it properties that are stored client sided. Concluding, the util provides you the method for setting the skin and it is up to you what you do next, if you call it sync or async, etc.
> 
> If this still confuses you, we can look at your code together to accomplish your desired outcome.
> 
> Note: never call getSync when on the main bukkit thread.
> 
> Kind regards.

So, how would I get the skin in async as done before? I tried calling the whole thing inside an other thread so it doesn't run on the  main thread, but it  still looks like it does.

Here is my actual code:
```java
new BukkitRunnable() {
	@Override
	public void run()
	{
		try
		{
			menuNPC.setDisplayName(player.getName());
			menuNPC.getProfile().getProperties().removeAll("textures");
			menuNPC.setSkinByUsername(instance, player.getName()).getSync();
			menuNPC.reloadNPC(player);
		}
		catch(Exception e)
		{
			throw new RuntimeException(e);
		}
	}
}.runTaskAsynchronously(instance);
```

This code does change the npc skin. But it also cause a lag spike.

**Comment by DanielTheDev** [comment]
I find it very strange since my code shouldn't be executed on the main thread. Can you print out the Thead.current::name inside the SkinTexture getByUsername and getByUUID since that should confirm my suspicions.

**Comment by ZeTioZ** [comment]
> 

Woops, sorry, I forgot to change the .jar inside my server. It was the previous version where I did not made it async... (I decompiled the jar inside the server cause it looked strange and I saw it was lacking the async call)

**Comment by DanielTheDev** [comment]
Haha, can happen. I'm glad it worked out well.
If you have any more questions or encounter more problems, I'm more than happy to help you.

Kind regards,
Daniël.

**Comment by ZeTioZ** [comment]
> Haha, can happen. I'm glad it worked out well. If you have any more questions or encounter more problems, I'm more than happy to help you.
> 
> Kind regards, Daniël.

Thanks a lot for your help!
